### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by haliaga1** [ArcherGu/node-red-contrib-socketio-server#1]
Archer, great job!

I get an error, but maybe have a wrong implementation. Have any example flows?
In my example clients connects, but i no get any connection status in server side.

![image](https://user-images.githubusercontent.com/9422455/111838779-9344b880-88d8-11eb-8118-46e571861cc2.png)

In advance, thanks!!

Here my example:
[{"id":"d71689f8.cd2318","type":"socket.io-middleware-start","z":"e7318376.92e94","name":"sio","instance":"19a5eb9b.0127d4","namespace":"","x":150,"y":60,"wires":[["b26f4c72.4a718"]]},{"id":"76814b5a.8e9b54","type":"socket.io-middleware-end","z":"e7318376.92e94","name":"sio","x":510,"y":60,"wires":[]},{"id":"ea3ceda0.98078","type":"debug","z":"e7318376.92e94","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":830,"y":60,"wires":[]},{"id":"7ad01964.d73c68","type":"link in","z":"e7318376.92e94","name":"","links":["8420922b.14ae6","6242fca9.33ec64","12ef2c3f.2d8804","e86e84f9.975ed8","ca961d8a.9cc4a","a58b18cf.ebb2d8"],"x":715,"y":60,"wires":[["ea3ceda0.98078"]]},{"id":"adb8d90c.ac3a28","type":"socket.io-join-room","z":"e7318376.92e94","name":"santiago","room":"santiago","x":340,"y":140,"wires":[[]]},{"id":"15e34694.1c6df9","type":"inject","z":"e7318376.92e94","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"{\"test\":\"ok\"}","payloadType":"json","x":170,"y":140,"wires":[["adb8d90c.ac3a28"]]},{"id":"6475eff1.bbeb2","type":"socket.io-emit","z":"e7318376.92e94","name":"","instance":"19a5eb9b.0127d4","event":"agenda admision","namespace":"","room":"santiago","x":380,"y":340,"wires":[]},{"id":"5a83e882.219188","type":"inject","z":"e7318376.92e94","name":"agenda test","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"agenda\":[{\"ticket\":\"A001\",\"nombre\":\"Hugo\",\"rut\":\"1-9\"},{\"ticket\":\"A002\",\"nombre\":\"Alfonso\",\"rut\":\"2-7\"}]}","payloadType":"json","x":170,"y":340,"wires":[["6475eff1.bbeb2"]]},{"id":"eb4d7ded.2238f","type":"socket.io-on","z":"e7318376.92e94","name":"agenda admision","instance":"19a5eb9b.0127d4","event":"agenda admision","namespace":"","x":160,"y":260,"wires":[["e86e84f9.975ed8"]]},{"id":"e86e84f9.975ed8","type":"link out","z":"e7318376.92e94","name":"","links":["7ad01964.d73c68"],"x":315,"y":260,"wires":[]},{"id":"b26f4c72.4a718","type":"function","z":"e7318376.92e94","name":"","func":"\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":320,"y":60,"wires":[["76814b5a.8e9b54","a58b18cf.ebb2d8"]]},{"id":"a58b18cf.ebb2d8","type":"link out","z":"e7318376.92e94","name":"","links":["7ad01964.d73c68"],"x":455,"y":100,"wires":[]},{"id":"19a5eb9b.0127d4","type":"socket.io-instance","z":"","name":"","port":"3000","options":"{\n  \"cors\": {\n    \"origins\": [\"*\"]\n  }\n}"}]

**Comment by ArcherGu** [comment]
Hi, @haliaga1 , thx for your issues. In fact, I don't think [node-red-contrib-socketio-server ](https://github.com/ArcherGu/node-red-contrib-socketio-server)or socket.io cause it. You can just remove the link to debug node, or `delete msg.socket` in your middleware handle function node then to print it.

According to my guess, debug node will loop through the entire msg object, but unfortunately the msg.socket provided by the middleware contains a very deep nested loop, which can lead to the problem you're talking about. 

Here's my modified flow:
```json
[{"id":"a83876fe.ed6448","type":"tab","label":"test","disabled":false,"info":""},{"id":"d71689f8.cd2318","type":"socket.io-middleware-start","z":"a83876fe.ed6448","name":"sio","instance":"19a5eb9b.0127d4","namespace":"test","x":350,"y":160,"wires":[["b26f4c72.4a718"]]},{"id":"76814b5a.8e9b54","type":"socket.io-middleware-end","z":"a83876fe.ed6448","name":"sio","x":690,"y":160,"wires":[]},{"id":"ea3ceda0.98078","type":"debug","z":"a83876fe.ed6448","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1030,"y":160,"wires":[]},{"id":"7ad01964.d73c68","type":"link in","z":"a83876fe.ed6448","name":"","links":["a58b18cf.ebb2d8","e86e84f9.975ed8","497bec88.c3e114"],"x":895,"y":160,"wires":[["ea3ceda0.98078"]]},{"id":"adb8d90c.ac3a28","type":"socket.io-join-room","z":"a83876fe.ed6448","name":"santiago","room":"santiago","x":520,"y":280,"wires":[[]]},{"id":"15e34694.1c6df9","type":"inject","z":"a83876fe.ed6448","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"{\"test\":\"ok\"}","payloadType":"json","x":350,"y":280,"wires":[["adb8d90c.ac3a28"]]},{"id":"6475eff1.bbeb2","type":"socket.io-emit","z":"a83876fe.ed6448","name":"","instance":"19a5eb9b.0127d4","event":"agenda admision","namespace":"","room":"santiago","x":580,"y":440,"wires":[]},{"id":"5a83e882.219188","type":"inject","z":"a83876fe.ed6448","name":"agenda test","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"agenda\":[{\"ticket\":\"A001\",\"nombre\":\"Hugo\",\"rut\":\"1-9\"},{\"ticket\":\"A002\",\"nombre\":\"Alfonso\",\"rut\":\"2-7\"}]}","payloadType":"json","x":370,"y":440,"wires":[["6475eff1.bbeb2"]]},{"id":"eb4d7ded.2238f","type":"socket.io-on","z":"a83876fe.ed6448","name":"agenda admision","instance":"19a5eb9b.0127d4","event":"agenda admision","namespace":"","x":360,"y":360,"wires":[["e86e84f9.975ed8"]]},{"id":"e86e84f9.975ed8","type":"link out","z":"a83876fe.ed6448","name":"","links":["7ad01964.d73c68"],"x":515,"y":360,"wires":[]},{"id":"b26f4c72.4a718","type":"function","z":"a83876fe.ed6448","name":"","func":"delete msg.socket\n\n// Don't forget to set up payload\nmsg.payload = true;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":520,"y":160,"wires":[["76814b5a.8e9b54","a58b18cf.ebb2d8"]]},{"id":"a58b18cf.ebb2d8","type":"link out","z":"a83876fe.ed6448","name":"","links":["7ad01964.d73c68"],"x":655,"y":240,"wires":[]},{"id":"f23c6309.2146","type":"comment","z":"a83876fe.ed6448","name":"or you can just unlink this to debug node","info":"","x":840,"y":240,"wires":[]},{"id":"19a5eb9b.0127d4","type":"socket.io-instance","name":"","port":"3000","options":"{\n \"cors\": {\n \"origins\": [\"*\"]\n }\n}"}]
```

**Comment by haliaga1** [comment]
thanks, now i understand how is implemented.
