### ISSUE TITLE
Additional Information

### ISSUE THREAD

**Issue by e-labInnovations** [ArcherGu/node-red-contrib-socketio-server#2]
Thank you for this wonderful node :heart_eyes:

### Requesting to add one or more examples
- simple flow
- advanced flow with rooms (like [this](https://youtu.be/jD7FnbI76Hg))

### Some doubts
- Can create multiple instances with different path and namespace and work independently with single port?
(One of my Node-Red server working on heroku which is port 80)
- is this a advanced version of node-red-contrib-socketio ?

**Comment by ArcherGu** [comment]
Hi, @e-labInnovations. Thank you very much for your suggestion, I've added a simple tutorial and example flow to repository. You can see [here](https://github.com/ArcherGu/node-red-contrib-socketio-server/tree/main/tutorial).

**About your doubts**
- An instance can bind only one port. You can add some identifying information to the client connection query, or token for the client, which you can use to add the client to the specified room when the client is connected.

```js
const socket = io("your_url", {
    auth: {
        token: "the_token_you_can_identify_the_client",
    },
    query: {
        room: 'the_room_you_want_to_join'
    },
});
```

- The current version is Socket.IO v4.x, which appears to be the [latest version](https://socket.io/docs/v4/server-installation/).😀

**Comment by e-labInnovations** [comment]
@ArcherGu 
Thank you for your response and efforts:heart_eyes:
The provided example is not in correct formate. Usually a node example flows are located in  ```/examples``` folder with JSON extention or you can publish on
 ```https://flows.nodered.org/flow/```. 


Please check this example
[https://flows.nodered.org/flow/71f7da3a14951acb67f94bac1f71812a](https://flows.nodered.org/flow/71f7da3a14951acb67f94bac1f71812a)

It provides both client side and server side codes in a single flow. 


I tried your node with my Node-Red running on my pc with origin ```http://localhost:1880``` and a client running on the same pc with origin ```http://localhost:8080``` (using live-server installed on globally with npm). But it fail to connect to my Node-Red server. After adding socket.io instance option to 
``` JSON
{
   "cors" : { "origin" : "http://localhost:8080"}
}
```
client connected tho server successfully.

But the problem that my original Node-Red server running on heroku. i.e port 80 (http) or with SSL port 443 (https). And the client can't connect to the server because of Cross-Origin problem. I tried with 

```
{
   "cors" : { "origin" : "http://localhost:8080"}
}
```

And 


```
{
   "cors" : { "origin" : "*"}
}
```


Nothing worked.

Can you give me a better example

**Comment by ArcherGu** [comment]
@e-labInnovations Hi, here is the [example flow](https://flows.nodered.org/flow/e65be16b8f2a83f61f0c2ad93bb52d1a).

This package only implements the server of the socket.io. No client node is available for use.

Cross-Origin problem is about the options for the socket.io itself, and the [example flow](https://flows.nodered.org/flow/e65be16b8f2a83f61f0c2ad93bb52d1a) provided has a related configuration that I can use normally here.
```json
{
    "cors": {
        "origin": "*",
        "credentials": false
    }
}
```

In fact, this package is already in use in my production environment and is working well.

**Comment by e-labInnovations** [comment]
Thank you so much for your effort and kind ♥️

Can you please give the client code you are used for testing?
 
> In fact, this package is already in use in my production environment and is working well.

Which production environment you are using?


Can you test this node in heroku?
Please use this link for Node-Red  heroku app
[https://github.com/joeartsea/node-red-heroku](https://github.com/joeartsea/node-red-heroku)
Or just tap below
[![Deploy](https://www.herokucdn.com/deploy/button.png)](https://heroku.com/deploy?template=https://github.com/joeartsea/node-red-heroku)

**Comment by ArcherGu** [comment]
@e-labInnovations Sorry for my late reply.

I create a small chat demo, you can find [here](https://archergu.github.io/node-red-contrib-socketio-server/).
I've also added [it and a little flow](https://github.com/ArcherGu/node-red-contrib-socketio-server/tree/main/examples) to the repository.

How to use: 
- Import the chat demo flow to your node-red.
- Open two tabs with this demo page on your browser.
- Enter the address of the socket.io in node-red, your name and your friend's name (just imaginary names like Tom and Jerry😀).
- Swap names on another tab, don't forget the address.
- Try it.
<img width="800" src="https://github.com/ArcherGu/node-red-contrib-socketio-server/blob/main/tutorial/images/chat-demo.png" alt="logo">

**Comment by e-labInnovations** [comment]
Awesome work @ArcherGu 
I love your Ui work and your effort.
It working on my pc as expected. But not working on Heroku. Can you add the bind to the node-red server option (`bindToNode`) by using a check box on the socket.io server instance?
![image](https://user-images.githubusercontent.com/33958126/118221605-91900f00-b49b-11eb-98cf-4f4df37eef5c.png)
``` JavaScript
if (this.bindToNode || Number(RED.settings.uiPort) == this.port) {
    this.instance = socketio(RED.server, this.options);
    node.log("Socket.IO server will bind to Node-Red");
}
else {
    this.instance = socketio(this.port, this.options);
}
node.log("Created Socket.IO server at " + this.port);
```
https://github.com/ArcherGu/node-red-contrib-socketio-server/blob/546537c4b8bd909461c70b03ae2cd7e6e8ab13e6/socketio.js#L29

On Heroku, the node-red UI port always changes, I wish to bind on the node-red UI port
I tried port 1880, but can't connect due to the cors problem.
 I tried 
```
{
    "cors": {
        "origin": "*",
        "credentials": false
    }
}
```

or
Can you try with Heroku?

**Comment by ArcherGu** [comment]
Hi, @e-labInnovations
I've added the feature that bind to node-red port. [0.1.5](https://flows.nodered.org/node/node-red-contrib-socketio-server)

And I also deployed an example flow on Heroku.
Everything works well and you can try my Heroku url on the [chat demo](https://archergu.github.io/node-red-contrib-socketio-server/):  
[https://node-red-for-hero-ku.herokuapp.com/](https://node-red-for-hero-ku.herokuapp.com/)

**Comment by e-labInnovations** [comment]
Hi @ArcherGu 
Thank you so much :heart_eyes:
Any changes in flow?
Old flow working?
What change you made for working Node-Red socketio in heroku?

**Comment by ArcherGu** [comment]
@e-labInnovations Nothing has changed, just binding the port to the instance of node-red. You can use this example [flow](https://github.com/ArcherGu/node-red-contrib-socketio-server/blob/main/examples/chat_room.json), and bind port to node-red.

**Comment by e-labInnovations** [comment]
@ArcherGu 
Thank you
