### ISSUE TITLE
compare with node-red-contrib-socketio

### ISSUE THREAD

**Issue by tve** [ArcherGu/node-red-contrib-socketio-server#3]
Can you tell me how your module differs from node-red-contrib-socketio https://github.com/wperw/node-red-contrib-socketio ? Thanks!

**Comment by ArcherGu** [comment]
@tve [node-red-contrib-socketio](https://github.com/wperw/node-red-contrib-socketio) is a very good node-red-node.

But it's using older versions of SocketIO, and some APIs are no longer compatible.

Keep it easy, it's just another node-red-node that you can choose what you need to use. 😀

**Comment by tve** [comment]
FYI, there are forks that updated it to newer versions of socketio, such as https://github.com/wiktorschmidt/node-red-contrib-socketio
No complaints, I was just wondering whether you had different goals and was wondering about that.

**Comment by ArcherGu** [comment]
Thank you for the information, I didn't know it was forked.

There seems to be a lot in common, and I've added a middleware feature here
